baseURL = 'https://arithmego.com/'
languageCode = 'en-us'
title = 'ArithmeGo'

[params]
  description = 'Terminal-based arithmetic game for developers'
  github = 'https://github.com/gurselcakar/arithmego'
  twitter = 'https://x.com/gurselcakar'
  twitterHandle = '@gurselcakar'
  latestVersion = '0.7.0'

[menu]
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/gurselcakar/arithmego'
    weight = 1
    [menu.main.params]
      external = true
  [[menu.main]]
    name = 'Download'
    url = '/download/'
    weight = 2

[taxonomies]

[pagination]
  pagerSize = 20
